version: "3.7"

services:
  simsequencer:
    container_name: sequencer
    image: lagrange-node
    networks:
      localnet:
        ipv4_address: 192.168.20.2
    ports:
      - 8082:8080
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-sequencer"
    environment:
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_STORE_DBPATH=mongodb://192.168.20.101:27017
      - LAGRANGE_NODE_SEQUENCER_ETHEREUMURL=http://192.168.20.100:8545
  simavs-sync:
    container_name: avs-sync
    image: lagrangelabs/avs-sync:main
    networks:
      localnet:
        ipv4_address: 192.168.20.50
    command:
      - "/bin/sh"
      - "-c"
      - "/app/avs-sync"
    environment:
      - AVS_SYNC_SYNCHRONIZER_PRIVATEKEY=0x897ae21c31176946115ad9174145c2e8b755e1be0c1b4987a63db790349e8e15
      - AVS_SYNC_SYNCHRONIZER_RPCENDPOINT=http://192.168.20.100:8545
      - AVS_SYNC_SYNCHRONIZER_EIGENDELEGATIONMANAGERADDRESS=0xF2740f6A6333c7B405aD7EfC68c74adAd83cC30D
      - AVS_SYNC_SYNCHRONIZER_LAGRANGESTAKEMANAGERADDRESS=0x2445aC9Eb7Bcb502EbabCb63844eFe4049270f93
      - AVS_SYNC_SYNCHRONIZER_LAGRANGESERVICEADDRESS=0xBda41273d671bb33374F7b9C4Ae8746c712727f7
      - AVS_SYNC_SYNCHRONIZER_VOTEWEIGHERADDRESS=0x47836868bCC9Fd592824444D0F428012d3b057f1
      - AVS_SYNC_SYNCHRONIZER_COMMITTEEADDRESS=0xBF4E09354df24900e3d2A1e9057a9F7601fbDD06
      - AVS_SYNC_SYNCHRONIZER_SYNCINTERVAL=2
      - AVS_SYNC_SYNCHRONIZER_RETRYTIMEINTERVAL=2
  simserver:
    container_name: server
    image: lagrange-node
    networks:
      localnet:
        ipv4_address: 192.168.20.3
    volumes:
      - ./testutil/vector/config:/app/config
    ports:
      - 9090:9090
      - 6061:6060
      - 8083:8080
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-server"
    environment:
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_STORE_DBPATH=mongodb://192.168.20.101:27017
      - LAGRANGE_NODE_CONSENSUS_PROPOSERBLSKEYSTOREPATH=/app/config/bls_0.json
      - LAGRANGE_NODE_CONSENSUS_PROPOSERBLSKEYSTOREPASSWORD=password_localtest
      - LAGRANGE_NODE_SEQUENCER_ETHEREUMURL=http://192.168.20.100:8545
  simserver1:
    container_name: server1
    image: lagrange-node
    networks:
      localnet:
        ipv4_address: 192.168.20.33
    volumes:
      - ./testutil/vector/config:/app/config
    ports:
      - 9092:9090
      - 6062:6060
      - 8085:8080
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-server"
    environment:
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_STORE_DBPATH=mongodb://192.168.20.101:27017
      - LAGRANGE_NODE_CONSENSUS_PROPOSERBLSKEYSTOREPATH=/app/config/bls_0.json
      - LAGRANGE_NODE_CONSENSUS_PROPOSERBLSKEYSTOREPASSWORD=password_localtest
  simnode1:
    container_name: node0
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURLS=192.168.20.3:9090,192.168.20.33:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=0.42s
      - LAGRANGE_NODE_CLIENT_OPERATORADDRESS=0x516D6C27C23CEd21BF7930E2a01F0BcA9A141a0d
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPATH=/app/config/bls_1.json
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPATH=/app/config/ecdsa_1.json
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_CLIENT_ETHEREUMURL=http://192.168.20.100:8545
    networks:
      localnet:
        ipv4_address: 192.168.20.4
    volumes:
      - ./testutil/vector/config:/app/config
    ports:
      - 8084:8080
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode2:
    container_name: node1
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURLS=192.168.20.3:9090,192.168.20.33:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=0.5s
      - LAGRANGE_NODE_CLIENT_OPERATORADDRESS=0x4d694DE17246086d6451D732Ea8EA2a9a76dC997
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPATH=/app/config/bls_2.json
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPATH=/app/config/ecdsa_2.json
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_CLIENT_ETHEREUMURL=http://192.168.20.100:8545
    networks:
      localnet:
        ipv4_address: 192.168.20.5
    volumes:
      - ./testutil/vector/config:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode3:
    container_name: node2
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURLS=192.168.20.3:9090,192.168.20.33:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=0.43s
      - LAGRANGE_NODE_CLIENT_OPERATORADDRESS=0x5d51B4c1fb0c67d0e1274EC96c1B895F45505a3D
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPATH=/app/config/bls_3.json
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPATH=/app/config/ecdsa_3.json
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_CLIENT_ETHEREUMURL=http://192.168.20.100:8545
    networks:
      localnet:
        ipv4_address: 192.168.20.6
    volumes:
      - ./testutil/vector/config:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode4:
    container_name: node3
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURLS=192.168.20.3:9090,192.168.20.33:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=0.35s
      - LAGRANGE_NODE_CLIENT_OPERATORADDRESS=0x13cF11F76a08214A826355a1C8d661E41EA7Bf97
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPATH=/app/config/bls_4.json
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPATH=/app/config/ecdsa_4.json
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_CLIENT_ETHEREUMURL=http://192.168.20.100:8545
    networks:
      localnet:
        ipv4_address: 192.168.20.7
    volumes:
      - ./testutil/vector/config:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode5:
    container_name: node4
    image: lagrangelabs/lagrange-node:v1.0.0
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURLS=192.168.20.3:9090,192.168.20.33:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=0.23s
      - LAGRANGE_NODE_CLIENT_OPERATORADDRESS=0xBD2369a9535751004617bC47cB0BF8Ea5c35Ed7C
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPATH=/app/config/bls_5.json
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPATH=/app/config/ecdsa_5.json
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_CLIENT_ETHEREUMURL=http://192.168.20.100:8545
    networks:
      localnet:
        ipv4_address: 192.168.20.8
    volumes:
      - ./testutil/vector/config:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode6:
    container_name: node5
    image: lagrangelabs/lagrange-node:v1.0.0
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURLS=192.168.20.3:9090,192.168.20.33:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=0.38s
      - LAGRANGE_NODE_CLIENT_OPERATORADDRESS=0x83070c799c0d41526D4c71e462557CdbB2C750AC
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPATH=/app/config/bls_6.json
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPASSWORD=password
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPATH=/app/config/ecdsa_6.json
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPASSWORDPATH=/app/config/keystore_password
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_CLIENT_ETHEREUMURL=http://192.168.20.100:8545
    networks:
      localnet:
        ipv4_address: 192.168.20.9
    volumes:
      - ./testutil/vector/config:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  simnode7:
    container_name: node6
    image: lagrange-node
    environment:
      - LAGRANGE_NODE_CLIENT_GRPCURLS=192.168.20.3:9090,192.168.20.33:9090
      - LAGRANGE_NODE_CLIENT_PULLINTERVAL=0.47s
      - LAGRANGE_NODE_CLIENT_OPERATORADDRESS=0x7365666466f97E8aBBEE8900925521e0469A1f25
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPATH=/app/config/bls_7.json
      - LAGRANGE_NODE_CLIENT_BLSKEYSTOREPASSWORD=password_localtest
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPATH=/app/config/ecdsa_7.json
      - LAGRANGE_NODE_CLIENT_SIGNERECDSAKEYSTOREPASSWORD=password_localtest
      - LAGRANGE_NODE_RPCCLIENT_MOCK_RPCURL=http://192.168.20.100:8545
      - LAGRANGE_NODE_CLIENT_ETHEREUMURL=http://192.168.20.100:8545
    networks:
      localnet:
        ipv4_address: 192.168.20.10
    volumes:
      - ./testutil/vector/config:/app/config
    command:
      - "/bin/sh"
      - "-c"
      - "/app/lagrange-node run-client"
  lagrangesc:
    container_name: lagrange-smart-contract
    image: lagrangelabs/lagrange-contracts:develop
    networks:
      localnet:
        ipv4_address: 192.168.20.100
    ports:
      - "8545:8545"
  mongo:
    image: mongo:4.4
    container_name: mongo
    networks:
      localnet:
        ipv4_address: 192.168.20.101
    ports:
      - "27017:27017"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9091:9090"
    networks:
      localnet:
        ipv4_address: 192.168.20.102
  grafana:
    container_name: grafana
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    networks:
      localnet:
        ipv4_address: 192.168.20.103

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/25
